version: "3.4"

services:
  api:
    image: ohmycthulhu/game_api:1.1.4
    environment:
      - DB_USERNAME=qarishiqsozapp
      - DB_PASSWORD=5lynlzv9ply2
      - DB_HOST=192.168.12.8
      - DB_CONNECTION=mysql
      - DB_DATABASE=simtoday
      - HOST=0.0.0.0
      - MINIMAL_TRIES=-10000
    networks:
      - default
  knife:
    image: ohmycthulhu/knife_socket:2.11.3
    environment:
      - API_URL=http://api
      - PORT=3001
      - TYPE=en
      - MINIMAL_TRIES=0
    networks:
      - default
    ports:
      - "5000:3001"
  duck:
    image: ohmycthulhu/duckhit:2.6.3
    ports:
      - "6000:3000"
    environment:
      - SERVER_URL=http://api
    networks:
      - default

networks:
  default:
