version: "3.4"

services:
  api:
    build: api/.
    environment:
      - DB_USER=user
      - DB_PASSWORD=
      - DB_HOST=192.168.1.13
      - DB_CONNECTION=mysql
      - DB_DATABASE=knife
      - HOST=0.0.0.0
    networks:
      - default
  socket:
    build: socket/.
    environment:
      - API_URL=http://api:3333
    networks:
      - default
    ports:
      - "3210:3000"

networks:
  default:
