version: "3.4"

services:
  api:
    build: ../api/.
    environment:
      - DB_USER=user
      - DB_PASSWORD=s#C%2j6x4&
      - DB_HOST=192.168.1.128
      - DB_CONNECTION=mysql
      - DB_DATABASE=knife
      - HOST=0.0.0.0
      - MINIMAL_TRIES=-100
    networks:
      - default
  socket:
    build: ../knife/.
    environment:
      - API_URL=http://api
      - PORT=3000
      - TYPE=en
      - MINIMAL_TRIES=0
      - SESSION_DRIVER=redis
      - SESSION_SECRET=some_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - default
    deploy:
      replicas: 2
    ports:
      - "3210:3000"
  redis:
    image: redis:6.2
    networks:
      - default

networks:
  default:
