version: "3.4"

services:
  api:
    image: ohmycthulhu/knife_api:1.4.1
    environment:
      - DB_USER=knifeuser
      - DB_PASSWORD=6}aQ^P)w!;
      - DB_HOST=172.20.17.111
      - DB_CONNECTION=mysql
      - DB_DATABASE=knife
      - HOST=0.0.0.0
      - MINIMAL_TRIES=-10000
    networks:
      - default
  socket:
    image: ohmycthulhu/knife_socket:2.6.2
    environment:
      - API_URL=http://api:3333
      - PORT=3000
      - TYPE=en
      - MINIMAL_TRIES=-10000
    networks:
      - default
    ports:
      - "5000:3000"

networks:
  default:
